package skywolf46.extrautility.core.test.exceptions

class TestFailedException : RuntimeException()